/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Book, CirculationRecord, StudentSubmission, Announcement } from './types';

export const initialBooks: Book[] = [
  {
    id: 'book-1',
    title: 'Things Fall Apart',
    author: 'Chinua Achebe',
    isbn: '978-0385474542',
    category: 'African Literature',
    totalCopies: 10,
    availableCopies: 8,
    description: 'A landmark African masterpiece chronicling Okonkwo and pre-colonial life in southeastern Nigeria during the arrival of European missionaries and administrators.',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=700',
    readsCount: 148,
    deweyClass: '800',
    deweyCode: '896.3',
    ageRange: 'Ages 12-18+',
    readingLevel: 'Lexile 890L',
    pageCount: 209,
    themeColor: 'amber',
    rating: 4.9,
    hasAudio: true,
  },
  {
    id: 'book-2',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '978-0743273565',
    category: 'Classics',
    totalCopies: 5,
    availableCopies: 3,
    description: 'Set in the glamorous Jazz Age on Long Island, exploring the opulent wealth, illusions, and tragic longing of the enigmatic Jay Gatsby.',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=700',
    readsCount: 92,
    deweyClass: '800',
    deweyCode: '813.52',
    ageRange: 'Ages 14-18',
    readingLevel: 'Lexile 1070L',
    pageCount: 180,
    themeColor: 'indigo',
    rating: 4.8,
  },
  {
    id: 'book-3',
    title: 'Percy Jackson: The Lightning Thief',
    author: 'Rick Riordan',
    isbn: '978-0786838653',
    category: 'Fantasy & Adventure',
    totalCopies: 8,
    availableCopies: 5,
    description: 'Percy discovers he is a modern demigod son of Poseidon and must retrieve Zeus\'s stolen master bolt in a quest spanning mythological monsters and Mount Olympus.',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=700',
    readsCount: 184,
    deweyClass: '800',
    deweyCode: '813.6',
    ageRange: 'Ages 8-14',
    readingLevel: 'Lexile 740L',
    pageCount: 375,
    themeColor: 'teal',
    rating: 4.95,
    hasAudio: true,
  },
  {
    id: 'book-4',
    title: 'The Secret Garden',
    author: 'Frances Hodgson Burnett',
    isbn: '978-0064401883',
    category: 'Children\'s Fiction',
    totalCopies: 6,
    availableCopies: 4,
    description: 'Orphaned Mary Lennox uncovers a walled, neglected garden on the Yorkshire Moors and brings it back to vibrant life with Dickon and Colin.',
    coverImage: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=700',
    readsCount: 65,
    deweyClass: '800',
    deweyCode: '823.8',
    ageRange: 'Ages 7-12',
    readingLevel: 'Lexile 710L',
    pageCount: 331,
    themeColor: 'emerald',
    rating: 4.7,
  },
  {
    id: 'book-5',
    title: 'Diary of a Wimpy Kid: Rodrick Rules',
    author: 'Jeff Kinney',
    isbn: '978-0810993136',
    category: 'Comics & Humor',
    totalCopies: 12,
    availableCopies: 9,
    description: 'Greg Heffley navigates the hilarious perils of middle school, sibling rivalry, and high school secrets in his illustrated private journal.',
    coverImage: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd3?auto=format&fit=crop&q=80&w=700',
    readsCount: 205,
    deweyClass: '800',
    deweyCode: '813.6',
    ageRange: 'Ages 7-13',
    readingLevel: 'Lexile 910L',
    pageCount: 217,
    themeColor: 'orange',
    rating: 4.9,
  },
  {
    id: 'book-6',
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    isbn: '978-0553380163',
    category: 'STEM & Space',
    totalCopies: 4,
    availableCopies: 4,
    description: 'Stephen Hawking guides readers through black holes, the Big Bang, general relativity, quantum mechanics, and the search for a unified theory of everything.',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=700',
    readsCount: 54,
    deweyClass: '500',
    deweyCode: '523.1',
    ageRange: 'Ages 13-18+',
    readingLevel: 'Lexile 1290L',
    pageCount: 212,
    themeColor: 'purple',
    rating: 4.85,
  },
  {
    id: 'book-7',
    title: 'Introduction to Algorithms (CLRS)',
    author: 'Thomas H. Cormen et al.',
    isbn: '978-0262033848',
    category: 'Coding & Tech',
    totalCopies: 4,
    availableCopies: 3,
    description: 'The foundational standard for algorithms, data structures, graph theory, and dynamic programming for ambitious secondary scholars.',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=700',
    readsCount: 45,
    deweyClass: '000',
    deweyCode: '005.1',
    ageRange: 'Senior School / Faculty',
    readingLevel: 'Advanced CS',
    pageCount: 1312,
    themeColor: 'blue',
    rating: 4.9,
  },
  {
    id: 'book-8',
    title: 'The Republic',
    author: 'Plato',
    isbn: '978-0140455113',
    category: 'Philosophy & Ethics',
    totalCopies: 3,
    availableCopies: 2,
    description: 'Socrates and his interlocutors examine the meaning of justice, the ideal city-state, the allegory of the cave, and the philosopher-king.',
    coverImage: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&q=80&w=700',
    readsCount: 28,
    deweyClass: '100',
    deweyCode: '184',
    ageRange: 'Senior School (Year 10-12)',
    readingLevel: 'Philosophy',
    pageCount: 416,
    themeColor: 'slate',
    rating: 4.6,
  },
  {
    id: 'book-9',
    title: 'The Wealth of Nations',
    author: 'Adam Smith',
    isbn: '978-0553585971',
    category: 'Economics & Society',
    totalCopies: 5,
    availableCopies: 4,
    description: 'The foundational inquiry into the nature and causes of national wealth, division of labor, productivity, and modern economic systems.',
    coverImage: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=700',
    readsCount: 37,
    deweyClass: '300',
    deweyCode: '330.1',
    ageRange: 'Senior School (Year 11-12)',
    readingLevel: 'Economics',
    pageCount: 520,
    themeColor: 'amber',
    rating: 4.5,
  },
  {
    id: 'book-10',
    title: 'Architects of the Web',
    author: 'Robert H. Reid',
    isbn: '978-0471191871',
    category: 'Coding & Tech',
    totalCopies: 6,
    availableCopies: 5,
    description: 'An exciting inside chronicle of the visionary engineers, browsers, and protocols that built the World Wide Web and digital revolution.',
    coverImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=700',
    readsCount: 71,
    deweyClass: '600',
    deweyCode: '604.2',
    ageRange: 'Ages 11-18',
    readingLevel: 'Lexile 1040L',
    pageCount: 384,
    themeColor: 'cyan',
    rating: 4.75,
  },
  {
    id: 'book-11',
    title: 'A History of West Africa',
    author: 'A.D. Nzemeke & E. Erhagbe',
    isbn: '978-9781234567',
    category: 'History & Culture',
    totalCopies: 8,
    availableCopies: 6,
    description: 'A comprehensive study of West African empires (Ghana, Mali, Songhai), trans-Saharan commerce, coastal kingdoms, and modern statehood.',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=700',
    readsCount: 112,
    deweyClass: '900',
    deweyCode: '966',
    ageRange: 'Ages 10-18',
    readingLevel: 'West African Studies',
    pageCount: 310,
    themeColor: 'amber',
    rating: 4.9,
  },
  {
    id: 'book-12',
    title: 'The Lion, the Witch and the Wardrobe',
    author: 'C.S. Lewis',
    isbn: '978-0064404990',
    category: 'Fantasy & Adventure',
    totalCopies: 9,
    availableCopies: 7,
    description: 'Four siblings step through a magic wardrobe into Narnia, a land frozen in eternal winter by the White Witch, awaiting the return of the Great Lion Aslan.',
    coverImage: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?auto=format&fit=crop&q=80&w=700',
    readsCount: 160,
    deweyClass: '800',
    deweyCode: '823.91',
    ageRange: 'Ages 8-12',
    readingLevel: 'Lexile 940L',
    pageCount: 206,
    themeColor: 'rose',
    rating: 4.95,
    hasAudio: true,
  }
];

export const initialCirculation: CirculationRecord[] = [
  {
    id: 'loan-1',
    learnerName: 'Chidi Okafor (Year 9)',
    bookId: 'book-2',
    bookTitle: 'The Great Gatsby',
    borrowDate: '2026-06-15',
    dueDate: '2026-06-29',
    status: 'borrowed',
    alertSent: false,
  },
  {
    id: 'loan-2',
    learnerName: 'Amina Bello (Primary 5)',
    bookId: 'book-4',
    bookTitle: 'The Secret Garden',
    borrowDate: '2026-06-05',
    dueDate: '2026-06-19',
    status: 'overdue',
    alertSent: true,
  },
  {
    id: 'loan-3',
    learnerName: 'Tunde Williams (Year 11)',
    bookId: 'book-1',
    bookTitle: 'Things Fall Apart',
    borrowDate: '2026-05-10',
    dueDate: '2026-05-24',
    returnDate: '2026-05-23',
    status: 'returned',
    alertSent: false,
  },
  {
    id: 'loan-4',
    learnerName: 'Sarah J. (Primary 4)',
    bookId: 'book-3',
    bookTitle: 'Percy Jackson: The Lightning Thief',
    borrowDate: '2026-06-20',
    dueDate: '2026-07-04',
    status: 'borrowed',
    alertSent: false,
  }
];

export const initialSubmissions: StudentSubmission[] = [
  {
    id: 'sub-1',
    authorName: 'Tunde Williams',
    gradeOrYear: 'Year 11',
    title: 'The Midnight Chronicles: A Mystery in Lagos',
    category: 'short-story',
    content: `The city never sleeps, but on this particular Tuesday, the silence in the library was deafening. Outside, the headlights of yellow Danfo buses painted long, golden streaks on the rain-slicked asphalt of Broad Street. Inside, Tunde sat hidden behind a mountain of encyclopedias.

He was waiting for the clock to strike midnight. The legends at Premier International said that at midnight, the old leather-bound volume on the highest shelf of Section D would emit a soft, cerulean glow. It was rumored to hold the secrets of the school's founders, and more importantly, the clue to the lost colonial pocketwatch.

As the heavy brass hands of the grandfather clock ticked toward twelve, Tunde held his breath. Then, a click. The lights flickered. On shelf 14, a crack of brilliant blue light burst through the dust...`,
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=600',
    createdAt: '2026-06-25T14:30:00Z',
    status: 'approved',
    likesCount: 24,
    comments: [
      {
        id: 'c-1',
        authorName: 'Chidi Okafor',
        content: 'This is brilliant, Tunde! I literally felt the tension. When is chapter 2 coming?',
        createdAt: '2026-06-25T16:00:00Z'
      },
      {
        id: 'c-2',
        authorName: 'Librarian Alabi',
        content: 'Superb narrative writing, Tunde. Your vocabulary is outstanding. Keep writing!',
        createdAt: '2026-06-26T09:12:00Z'
      }
    ]
  },
  {
    id: 'sub-2',
    authorName: 'Sarah J.',
    gradeOrYear: 'Primary 4',
    title: 'The Rain on the Zinc Roof',
    category: 'poetry',
    content: `Drumming, rhythmic, loud and clear,
A melody only the young can hear.
It starts with a patter, a warning, a tap,
Then rumbles and rolls like a thunderous clap.

The sky turns heavy, a blanket of grey,
Washing the heat of the long afternoon away.
Under the metal, we gather and listen,
As puddles outside begin to glisten.

It speaks of old rivers, of oceans so deep,
Singing the restless earth right back to sleep.`,
    imageUrl: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&q=80&w=600',
    createdAt: '2026-06-28T09:15:00Z',
    status: 'approved',
    likesCount: 56,
    comments: [
      {
        id: 'c-3',
        authorName: 'Amina Bello',
        content: 'I love this poem! It sounds just like my house during the rainy season.',
        createdAt: '2026-06-28T11:45:00Z'
      }
    ]
  },
  {
    id: 'sub-3',
    authorName: 'Leo Chen',
    gradeOrYear: 'Year 8',
    title: 'Future Premier School 2050',
    category: 'digital-art',
    content: 'An architectural vision of our beloved Premier International School twenty-four years into the future. It depicts eco-domes, hovering learning modules, and solar-active panels integrated into the brickwork, harmonizing old-school aesthetics with futuristic green technologies.',
    imageUrl: 'https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?auto=format&fit=crop&q=80&w=600',
    createdAt: '2026-06-27T11:00:00Z',
    status: 'approved',
    likesCount: 89,
    comments: []
  },
  {
    id: 'sub-4',
    authorName: 'Fatima Musa',
    gradeOrYear: 'Year 12',
    title: 'An Analysis of Climate Policy in West Africa',
    category: 'academic-essay',
    content: `Climate change presents an existential challenge to the ecological and macroeconomic stability of the West African sub-region. While national frameworks like Nigeria's Climate Change Act (2021) set ambitious carbon reduction targets, structural bottlenecks—specifically sub-optimal financing and enforcement deficits—undermine execution.

This paper assesses the efficacy of localized adaptation strategies in agricultural sectors, comparing the top-down initiatives with decentralized community-led forestry in Ghana and Senegal. We argue that sustainable resilience is highly correlated with community-level asset ownership rather than large-scale, externally managed infrastructure project intervention...`,
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=600',
    createdAt: '2026-06-29T16:45:00Z',
    status: 'approved',
    likesCount: 18,
    comments: [
      {
        id: 'c-4',
        authorName: 'Mr. Gabriel (English & Gov)',
        content: 'A thoroughly researched and maturely formulated treatise, Fatima. The comparative analysis is highly persuasive.',
        createdAt: '2026-06-30T08:30:00Z'
      }
    ]
  },
  {
    id: 'sub-5',
    authorName: 'Amina Bello',
    gradeOrYear: 'Primary 5',
    title: 'Whispers of the Savannah',
    category: 'poetry',
    content: `Golden grass dancing in the dry harmattan wind,
Leaving all the dust and memories behind.
The baobab stands like a wise old king,
Waiting to hear what the morning birds will sing.

Shadows of gazelles leap over the plain,
Praying to the sky for the first sweet rain.`,
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=600',
    createdAt: '2026-07-01T10:20:00Z',
    status: 'pending',
    likesCount: 0,
    comments: []
  },
  {
    id: 'sub-6',
    authorName: 'Kojo Mensah',
    gradeOrYear: 'Year 9',
    title: 'The Cosmic Canvas of Dreams',
    category: 'digital-art',
    content: 'This artwork blends digital oil painting and astronomical telemetry designs to represent how young students dream of space exploration and finding their own creative stars in the heavens.',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=600',
    createdAt: '2026-07-01T14:50:00Z',
    status: 'pending',
    likesCount: 0,
    comments: []
  }
];

export const initialAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Annual Literacy Week: Book Review Submissions Open!',
    content: 'We are thrilled to launch this year\'s Literacy Week! Students from all grades are invited to submit critical reviews of their favorite books. The top 3 reviews will win Amazon Kindle readers and custom star badges in the gallery.',
    date: '2026-06-30',
    category: 'info',
  },
  {
    id: 'ann-2',
    title: 'Overdue Books Return Window (No Penalty)',
    content: 'Librarian Alabi has declared an Amnesty Week! All books returned by July 10th will have outstanding overdue flags cleared with zero fines or library suspension. Please check your desks and backpacks.',
    date: '2026-06-29',
    category: 'alert',
  },
  {
    id: 'ann-3',
    title: 'Congratulations to Sarah J. (Poet of the Month!)',
    content: 'A huge round of applause to Sarah J. in Primary 4! Her poem "The Rain on the Zinc Roof" received over 50 likes in our school gallery and was selected by our English Department as the top piece this week.',
    date: '2026-06-28',
    category: 'achievement',
  }
];
