/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Book, CirculationRecord, StudentSubmission, Announcement, HeroSpotlightData } from './types';

export const initialHeroSpotlight: HeroSpotlightData = {
  id: 'spotlight-1',
  title: 'Things Fall Apart',
  subtitle: 'Featured Masterpiece & African Literature Spotlight',
  description: 'Immerse yourself in Chinua Achebe\'s towering African classic chronicling Igbo traditions, colonial tensions, and Okonkwo\'s legendary story with immersive audio narration.',
  featuredBookId: 'book-1',
  badgeText: '⭐ BOOK OF THE WEEK',
  bgGradient: 'from-blue-600 via-indigo-600 to-purple-600',
  coverUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=700'
};

export const initialBooks: Book[] = [
  {
    id: 'book-1',
    title: 'Things Fall Apart',
    author: 'Chinua Achebe',
    isbn: '978-0385474542',
    category: 'African Literature',
    totalCopies: 10,
    availableCopies: 8,
    description: 'A landmark African masterpiece chronicling Okonkwo and pre-colonial life in southeastern Nigeria during the arrival of European missionaries and administrators.',
    summary: 'A landmark African masterpiece chronicling Okonkwo and pre-colonial life in southeastern Nigeria during the arrival of European missionaries and administrators.',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=700',
    readsCount: 148,
    deweyClass: '800',
    deweyCode: '896.3',
    callNumber: '896.3 ACH',
    ageRange: 'Ages 12-18+',
    readingLevel: 'Lexile 890L',
    pageCount: 209,
    themeColor: 'amber',
    rating: 4.9,
    hasAudio: true,
    isAudiobook: true,
    isPopular: true,
    isNew: false,
    isTeacherPick: true,
  },
  {
    id: 'book-2',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '978-0743273565',
    category: 'Classics',
    totalCopies: 5,
    availableCopies: 3,
    description: 'Set in the glamorous Jazz Age on Long Island, exploring the opulent wealth, illusions, and tragic longing of the enigmatic Jay Gatsby.',
    summary: 'Set in the glamorous Jazz Age on Long Island, exploring the opulent wealth, illusions, and tragic longing of the enigmatic Jay Gatsby.',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=700',
    readsCount: 92,
    deweyClass: '800',
    deweyCode: '813.52',
    callNumber: '813.52 FIT',
    ageRange: 'Ages 14-18',
    readingLevel: 'Lexile 1070L',
    pageCount: 180,
    themeColor: 'indigo',
    rating: 4.8,
    isPopular: true,
    isNew: false,
    isTeacherPick: true,
  },
  {
    id: 'book-3',
    title: 'Percy Jackson: The Lightning Thief',
    author: 'Rick Riordan',
    isbn: '978-0786838653',
    category: 'Fantasy & Adventure',
    totalCopies: 8,
    availableCopies: 5,
    description: 'Percy discovers he is a modern demigod son of Poseidon and must retrieve Zeus\'s stolen master bolt in a quest spanning mythological monsters and Mount Olympus.',
    summary: 'Percy discovers he is a modern demigod son of Poseidon and must retrieve Zeus\'s stolen master bolt in a quest spanning mythological monsters and Mount Olympus.',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=700',
    readsCount: 184,
    deweyClass: '800',
    deweyCode: '813.6',
    callNumber: '813.6 RIO',
    ageRange: 'Ages 8-14',
    readingLevel: 'Lexile 740L',
    pageCount: 375,
    themeColor: 'teal',
    rating: 4.95,
    hasAudio: true,
    isAudiobook: true,
    isPopular: true,
    isNew: true,
  },
  {
    id: 'book-4',
    title: 'The Secret Garden',
    author: 'Frances Hodgson Burnett',
    isbn: '978-0064401883',
    category: 'Children\'s Fiction',
    totalCopies: 6,
    availableCopies: 4,
    description: 'Orphaned Mary Lennox uncovers a walled, neglected garden on the Yorkshire Moors and brings it back to vibrant life with Dickon and Colin.',
    summary: 'Orphaned Mary Lennox uncovers a walled, neglected garden on the Yorkshire Moors and brings it back to vibrant life with Dickon and Colin.',
    coverImage: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=700',
    readsCount: 65,
    deweyClass: '800',
    deweyCode: '823.8',
    callNumber: '823.8 BUR',
    ageRange: 'Ages 7-12',
    readingLevel: 'Lexile 710L',
    pageCount: 331,
    themeColor: 'emerald',
    rating: 4.7,
    isTeacherPick: true,
  },
  {
    id: 'book-5',
    title: 'Diary of a Wimpy Kid: Rodrick Rules',
    author: 'Jeff Kinney',
    isbn: '978-0810993136',
    category: 'Comics & Humor',
    totalCopies: 12,
    availableCopies: 9,
    description: 'Greg Heffley navigates the hilarious perils of middle school, sibling rivalry, and high school secrets in his illustrated private journal.',
    summary: 'Greg Heffley navigates the hilarious perils of middle school, sibling rivalry, and high school secrets in his illustrated private journal.',
    coverImage: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd3?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd3?auto=format&fit=crop&q=80&w=700',
    readsCount: 205,
    deweyClass: '800',
    deweyCode: '813.6',
    callNumber: '813.6 KIN',
    ageRange: 'Ages 7-13',
    readingLevel: 'Lexile 910L',
    pageCount: 217,
    themeColor: 'orange',
    rating: 4.9,
    isPopular: true,
    isNew: true,
  },
  {
    id: 'book-6',
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    isbn: '978-0553380163',
    category: 'STEM & Space',
    totalCopies: 4,
    availableCopies: 4,
    description: 'Stephen Hawking guides readers through black holes, the Big Bang, general relativity, quantum mechanics, and the search for a unified theory of everything.',
    summary: 'Stephen Hawking guides readers through black holes, the Big Bang, general relativity, quantum mechanics, and the search for a unified theory of everything.',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=700',
    readsCount: 54,
    deweyClass: '500',
    deweyCode: '523.1',
    callNumber: '523.1 HAW',
    ageRange: 'Ages 13-18+',
    readingLevel: 'Lexile 1290L',
    pageCount: 212,
    themeColor: 'purple',
    rating: 4.85,
    isTeacherPick: true,
  },
  {
    id: 'book-7',
    title: 'Introduction to Algorithms (CLRS)',
    author: 'Thomas H. Cormen et al.',
    isbn: '978-0262033848',
    category: 'Coding & Tech',
    totalCopies: 4,
    availableCopies: 3,
    description: 'The foundational standard for algorithms, data structures, graph theory, and dynamic programming for ambitious secondary scholars.',
    summary: 'The foundational standard for algorithms, data structures, graph theory, and dynamic programming for ambitious secondary scholars.',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=700',
    readsCount: 45,
    deweyClass: '000',
    deweyCode: '005.1',
    callNumber: '005.1 COR',
    ageRange: 'Senior School / Faculty',
    readingLevel: 'Advanced CS',
    pageCount: 1312,
    themeColor: 'blue',
    rating: 4.9,
    isTeacherPick: true,
  },
  {
    id: 'book-8',
    title: 'The Republic',
    author: 'Plato',
    isbn: '978-0140455113',
    category: 'Philosophy & Ethics',
    totalCopies: 3,
    availableCopies: 2,
    description: 'Socrates and his interlocutors examine the meaning of justice, the ideal city-state, the allegory of the cave, and the philosopher-king.',
    summary: 'Socrates and his interlocutors examine the meaning of justice, the ideal city-state, the allegory of the cave, and the philosopher-king.',
    coverImage: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&q=80&w=700',
    readsCount: 28,
    deweyClass: '100',
    deweyCode: '184',
    callNumber: '184 PLA',
    ageRange: 'Senior School (Year 10-12)',
    readingLevel: 'Philosophy',
    pageCount: 416,
    themeColor: 'slate',
    rating: 4.6,
    isTeacherPick: true,
  },
  {
    id: 'book-9',
    title: 'The Wealth of Nations',
    author: 'Adam Smith',
    isbn: '978-0553585971',
    category: 'Economics & Society',
    totalCopies: 5,
    availableCopies: 4,
    description: 'The foundational inquiry into the nature and causes of national wealth, division of labor, productivity, and modern economic systems.',
    summary: 'The foundational inquiry into the nature and causes of national wealth, division of labor, productivity, and modern economic systems.',
    coverImage: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=700',
    readsCount: 37,
    deweyClass: '300',
    deweyCode: '330.1',
    callNumber: '330.1 SMI',
    ageRange: 'Senior School (Year 11-12)',
    readingLevel: 'Economics',
    pageCount: 520,
    themeColor: 'amber',
    rating: 4.5,
  },
  {
    id: 'book-10',
    title: 'Architects of the Web',
    author: 'Robert H. Reid',
    isbn: '978-0471191871',
    category: 'Coding & Tech',
    totalCopies: 6,
    availableCopies: 5,
    description: 'An exciting inside chronicle of the visionary engineers, browsers, and protocols that built the World Wide Web and digital revolution.',
    summary: 'An exciting inside chronicle of the visionary engineers, browsers, and protocols that built the World Wide Web and digital revolution.',
    coverImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=700',
    readsCount: 71,
    deweyClass: '600',
    deweyCode: '604.2',
    callNumber: '604.2 REI',
    ageRange: 'Ages 11-18',
    readingLevel: 'Lexile 1040L',
    pageCount: 384,
    themeColor: 'cyan',
    rating: 4.75,
    isNew: true,
  },
  {
    id: 'book-11',
    title: 'A History of West Africa',
    author: 'A.D. Nzemeke & E. Erhagbe',
    isbn: '978-9781234567',
    category: 'History & Culture',
    totalCopies: 8,
    availableCopies: 6,
    description: 'A comprehensive study of West African empires (Ghana, Mali, Songhai), trans-Saharan commerce, coastal kingdoms, and modern statehood.',
    summary: 'A comprehensive study of West African empires (Ghana, Mali, Songhai), trans-Saharan commerce, coastal kingdoms, and modern statehood.',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=700',
    readsCount: 112,
    deweyClass: '900',
    deweyCode: '966',
    callNumber: '966 NZE',
    ageRange: 'Ages 10-18',
    readingLevel: 'West African Studies',
    pageCount: 310,
    themeColor: 'amber',
    rating: 4.9,
    isPopular: true,
    isTeacherPick: true,
  },
  {
    id: 'book-12',
    title: 'The Lion, the Witch and the Wardrobe',
    author: 'C.S. Lewis',
    isbn: '978-0064404990',
    category: 'Fantasy & Adventure',
    totalCopies: 9,
    availableCopies: 7,
    description: 'Four siblings step through a magic wardrobe into Narnia, a land frozen in eternal winter by the White Witch, awaiting the return of the Great Lion Aslan.',
    summary: 'Four siblings step through a magic wardrobe into Narnia, a land frozen in eternal winter by the White Witch, awaiting the return of the Great Lion Aslan.',
    coverImage: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?auto=format&fit=crop&q=80&w=700',
    readsCount: 160,
    deweyClass: '800',
    deweyCode: '823.91',
    callNumber: '823.91 LEW',
    ageRange: 'Ages 8-12',
    readingLevel: 'Lexile 940L',
    pageCount: 206,
    themeColor: 'rose',
    rating: 4.95,
    hasAudio: true,
    isAudiobook: true,
    isPopular: true,
    isNew: true,
  }
];

export const initialCirculation: CirculationRecord[] = [];

export const initialSubmissions: StudentSubmission[] = [];

export const initialAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Annual Literacy Week: Book Review Submissions Open!',
    content: 'We are thrilled to launch this year\'s Literacy Week! Students from all grades are invited to submit critical reviews of their favorite books. The top 3 reviews will win Amazon Kindle readers and custom star badges in the gallery.',
    date: '2026-06-30',
    category: 'info',
  },
  {
    id: 'ann-2',
    title: 'Overdue Books Return Window (No Penalty)',
    content: 'Librarian Alabi has declared an Amnesty Week! All books returned by July 10th will have outstanding overdue flags cleared with zero fines or library suspension. Please check your desks and backpacks.',
    date: '2026-06-29',
    category: 'alert',
  },
  {
    id: 'ann-3',
    title: 'Congratulations to Sarah J. (Poet of the Month!)',
    content: 'A huge round of applause to Sarah J. in Primary 4! Her poem "The Rain on the Zinc Roof" received over 50 likes in our school gallery and was selected by our English Department as the top piece this week.',
    date: '2026-06-28',
    category: 'achievement',
  }
];
