/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Book, CirculationRecord, StudentSubmission, Announcement, HeroSpotlightData } from './types';

export const initialHeroSpotlight: HeroSpotlightData = {
  id: 'spotlight-1',
  title: 'Things Fall Apart',
  subtitle: 'Featured Masterpiece & African Literature Spotlight',
  description: 'Immerse yourself in Chinua Achebe\'s towering African classic chronicling Igbo traditions, colonial tensions, and Okonkwo\'s legendary story with immersive audio narration.',
  featuredBookId: 'book-1',
  badgeText: '⭐ BOOK OF THE WEEK',
  bgGradient: 'from-blue-600 via-indigo-600 to-purple-600',
  coverUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=700'
};

export const DEMO_SAMPLE_IDS = new Set([
  'book-1', 'book-2', 'book-3', 'book-4', 'book-5',
  'book-6', 'book-7', 'book-8', 'book-9', 'book-10'
]);

export const initialBooks: Book[] = [
  {
    id: 'book-1',
    title: 'Things Fall Apart',
    author: 'Chinua Achebe',
    isbn: '978-0385474542',
    category: 'African Literature',
    section: 'college',
    totalCopies: 10,
    availableCopies: 8,
    description: 'A landmark African masterpiece chronicling Okonkwo and pre-colonial life in southeastern Nigeria during the arrival of European missionaries and administrators.',
    summary: 'A landmark African masterpiece chronicling Okonkwo and pre-colonial life in southeastern Nigeria during the arrival of European missionaries and administrators.',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=700',
    readsCount: 148,
    deweyClass: '800',
    deweyCode: '896.3',
    callNumber: '896.3 ACH',
    ageRange: 'Ages 12-18+',
    readingLevel: 'Lexile 890L',
    pageCount: 209,
    themeColor: 'amber',
    rating: 4.9,
    hasAudio: true,
    isAudiobook: true,
    isPopular: true,
    isNew: false,
    isTeacherPick: true,
  },
  {
    id: 'book-2',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '978-0743273565',
    category: 'Classics',
    section: 'college',
    totalCopies: 5,
    availableCopies: 3,
    description: 'Set in the glamorous Jazz Age on Long Island, exploring the opulent wealth, illusions, and tragic longing of the enigmatic Jay Gatsby.',
    summary: 'Set in the glamorous Jazz Age on Long Island, exploring the opulent wealth, illusions, and tragic longing of the enigmatic Jay Gatsby.',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=700',
    readsCount: 92,
    deweyClass: '800',
    deweyCode: '813.52',
    callNumber: '813.52 FIT',
    ageRange: 'Ages 14-18',
    readingLevel: 'Lexile 1070L',
    pageCount: 180,
    themeColor: 'indigo',
    rating: 4.8,
    isPopular: true,
    isNew: false,
    isTeacherPick: true,
  },
  {
    id: 'book-3',
    title: 'Percy Jackson: The Lightning Thief',
    author: 'Rick Riordan',
    isbn: '978-0786838653',
    category: 'Fantasy & Adventure',
    section: 'primary',
    totalCopies: 8,
    availableCopies: 5,
    description: 'Percy discovers he is a modern demigod son of Poseidon and must retrieve Zeus\'s stolen master bolt in a quest spanning mythological monsters and Mount Olympus.',
    summary: 'Percy discovers he is a modern demigod son of Poseidon and must retrieve Zeus\'s stolen master bolt in a quest spanning mythological monsters and Mount Olympus.',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=700',
    readsCount: 184,
    deweyClass: '800',
    deweyCode: '813.6',
    callNumber: '813.6 RIO',
    ageRange: 'Ages 8-14',
    readingLevel: 'Lexile 740L',
    pageCount: 375,
    themeColor: 'teal',
    rating: 4.95,
    hasAudio: true,
    isAudiobook: true,
    isPopular: true,
    isNew: true,
  },
  {
    id: 'book-4',
    title: 'The Secret Garden',
    author: 'Frances Hodgson Burnett',
    isbn: '978-0064401883',
    category: 'Children\'s Fiction',
    section: 'primary',
    totalCopies: 6,
    availableCopies: 4,
    description: 'Orphaned Mary Lennox uncovers a walled, neglected garden on the Yorkshire Moors and brings it back to vibrant life with Dickon and Colin.',
    summary: 'Orphaned Mary Lennox uncovers a walled, neglected garden on the Yorkshire Moors and brings it back to vibrant life with Dickon and Colin.',
    coverImage: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=700',
    readsCount: 65,
    deweyClass: '800',
    deweyCode: '823.8',
    callNumber: '823.8 BUR',
    ageRange: 'Ages 7-12',
    readingLevel: 'Lexile 710L',
    pageCount: 331,
    themeColor: 'emerald',
    rating: 4.7,
    isTeacherPick: true,
  },
  {
    id: 'book-5',
    title: 'Diary of a Wimpy Kid: Rodrick Rules',
    author: 'Jeff Kinney',
    isbn: '978-0810993136',
    category: 'Comics & Humor',
    section: 'primary',
    totalCopies: 12,
    availableCopies: 9,
    description: 'Greg Heffley navigates the hilarious perils of middle school, sibling rivalry, and high school secrets in his illustrated private journal.',
    summary: 'Greg Heffley navigates the hilarious perils of middle school, sibling rivalry, and high school secrets in his illustrated private journal.',
    coverImage: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd3?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd3?auto=format&fit=crop&q=80&w=700',
    readsCount: 205,
    deweyClass: '800',
    deweyCode: '813.6',
    callNumber: '813.6 KIN',
    ageRange: 'Ages 7-13',
    readingLevel: 'Lexile 910L',
    pageCount: 217,
    themeColor: 'orange',
    rating: 4.9,
    isPopular: true,
    isNew: true,
  },
  {
    id: 'book-6',
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    isbn: '978-0553380163',
    category: 'STEM & Space',
    section: 'college',
    totalCopies: 4,
    availableCopies: 4,
    description: 'Stephen Hawking guides readers through black holes, the Big Bang, general relativity, quantum mechanics, and the search for a unified theory of everything.',
    summary: 'Stephen Hawking guides readers through black holes, the Big Bang, general relativity, quantum mechanics, and the search for a unified theory of everything.',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=700',
    readsCount: 54,
    deweyClass: '500',
    deweyCode: '523.1',
    callNumber: '523.1 HAW',
    ageRange: 'Ages 13-18+',
    readingLevel: 'Lexile 1290L',
    pageCount: 212,
    themeColor: 'purple',
    rating: 4.85,
    isTeacherPick: true,
  },
  {
    id: 'book-7',
    title: 'Introduction to Algorithms (CLRS)',
    author: 'Thomas H. Cormen et al.',
    isbn: '978-0262033848',
    category: 'Coding & Tech',
    section: 'college',
    totalCopies: 4,
    availableCopies: 3,
    description: 'The foundational standard for algorithms, data structures, graph theory, and dynamic programming for ambitious secondary scholars.',
    summary: 'The foundational standard for algorithms, data structures, graph theory, and dynamic programming for ambitious secondary scholars.',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=700',
    readsCount: 45,
    deweyClass: '000',
    deweyCode: '005.1',
    callNumber: '005.1 COR',
    ageRange: 'Senior School / Faculty',
    readingLevel: 'Advanced CS',
    pageCount: 1312,
    themeColor: 'blue',
    rating: 4.9,
    isTeacherPick: true,
  },
  {
    id: 'book-8',
    title: 'The Republic',
    author: 'Plato',
    isbn: '978-0140455113',
    category: 'Philosophy & Ethics',
    section: 'college',
    totalCopies: 3,
    availableCopies: 2,
    description: 'Socrates and his interlocutors examine the meaning of justice, the ideal city-state, the allegory of the cave, and the philosopher-king.',
    summary: 'Socrates and his interlocutors examine the meaning of justice, the ideal city-state, the allegory of the cave, and the philosopher-king.',
    coverImage: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&q=80&w=700',
    readsCount: 28,
    deweyClass: '100',
    deweyCode: '184',
    callNumber: '184 PLA',
    ageRange: 'Senior School (Year 10-12)',
    readingLevel: 'Philosophy',
    pageCount: 416,
    themeColor: 'slate',
    rating: 4.6,
    isTeacherPick: true,
  },
  {
    id: 'book-9',
    title: 'The Wealth of Nations',
    author: 'Adam Smith',
    isbn: '978-0553585971',
    category: 'Economics & Society',
    section: 'college',
    totalCopies: 5,
    availableCopies: 4,
    description: 'The foundational inquiry into the nature and causes of national wealth, division of labor, productivity, and modern economic systems.',
    summary: 'The foundational inquiry into the nature and causes of national wealth, division of labor, productivity, and modern economic systems.',
    coverImage: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=700',
    readsCount: 37,
    deweyClass: '300',
    deweyCode: '330.1',
    callNumber: '330.1 SMI',
    ageRange: 'Senior School (Year 11-12)',
    readingLevel: 'Economics',
    pageCount: 520,
    themeColor: 'amber',
    rating: 4.5,
  },
  {
    id: 'book-10',
    title: 'Architects of the Web',
    author: 'Robert H. Reid',
    isbn: '978-0471191871',
    category: 'Coding & Tech',
    section: 'college',
    totalCopies: 6,
    availableCopies: 5,
    description: 'An exciting inside chronicle of the visionary engineers, browsers, and protocols that built the World Wide Web and digital revolution.',
    summary: 'An exciting inside chronicle of the visionary engineers, browsers, and protocols that built the World Wide Web and digital revolution.',
    coverImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=700',
    readsCount: 71,
    deweyClass: '600',
    deweyCode: '604.2',
    callNumber: '604.2 REI',
    ageRange: 'Ages 11-18',
    readingLevel: 'Lexile 1040L',
    pageCount: 384,
    themeColor: 'cyan',
    rating: 4.75,
    isNew: true,
  },
  {
    id: 'book-11',
    title: 'A History of West Africa',
    author: 'A.D. Nzemeke & E. Erhagbe',
    isbn: '978-9781234567',
    category: 'History & Culture',
    section: 'college',
    totalCopies: 8,
    availableCopies: 6,
    description: 'A comprehensive study of West African empires (Ghana, Mali, Songhai), trans-Saharan commerce, coastal kingdoms, and modern statehood.',
    summary: 'A comprehensive study of West African empires (Ghana, Mali, Songhai), trans-Saharan commerce, coastal kingdoms, and modern statehood.',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=700',
    readsCount: 112,
    deweyClass: '900',
    deweyCode: '966',
    callNumber: '966 NZE',
    ageRange: 'Ages 10-18',
    readingLevel: 'West African Studies',
    pageCount: 310,
    themeColor: 'amber',
    rating: 4.9,
    isPopular: true,
    isTeacherPick: true,
  },
  {
    id: 'book-12',
    title: 'The Lion, the Witch and the Wardrobe',
    author: 'C.S. Lewis',
    isbn: '978-0064404990',
    category: 'Fantasy & Adventure',
    section: 'primary',
    totalCopies: 9,
    availableCopies: 7,
    description: 'Four siblings step through a magic wardrobe into Narnia, a land frozen in eternal winter by the White Witch, awaiting the return of the Great Lion Aslan.',
    summary: 'Four siblings step through a magic wardrobe into Narnia, a land frozen in eternal winter by the White Witch, awaiting the return of the Great Lion Aslan.',
    coverImage: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?auto=format&fit=crop&q=80&w=700',
    readsCount: 160,
    deweyClass: '800',
    deweyCode: '823.91',
    callNumber: '823.91 LEW',
    ageRange: 'Ages 8-12',
    readingLevel: 'Lexile 940L',
    pageCount: 206,
    themeColor: 'rose',
    rating: 4.95,
    hasAudio: true,
    isAudiobook: true,
    isPopular: true,
    isNew: true,
  },
  {
    id: 'book-11',
    title: '14 Things Nigerian Youth Must Know',
    author: 'Seun Adeagbo',
    isbn: '978-978-020-981-0',
    category: 'African Literature',
    section: 'college',
    totalCopies: 19,
    availableCopies: 19,
    description: 'An essential, empowering roadmap for Nigerian youths exploring self-discovery, purpose, integrity, critical life skills, and academic and career excellence.',
    summary: 'An essential, empowering roadmap for Nigerian youths exploring self-discovery, purpose, integrity, critical life skills, and academic and career excellence.',
    coverImage: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&q=80&w=700',
    readsCount: 42,
    deweyClass: '300',
    deweyCode: '305.235',
    callNumber: '305.235 ADE',
    ageRange: 'Ages 13-18+',
    readingLevel: 'Lexile 860L',
    pageCount: 168,
    themeColor: 'emerald',
    rating: 4.85,
    isPopular: true,
    isNew: true,
    isTeacherPick: true,
  },
  {
    id: 'book-12',
    title: 'Career Guide',
    author: 'Felix Amajuoyi',
    isbn: '978-978-950-199-1',
    category: 'STEM & Space',
    section: 'college',
    totalCopies: 2,
    availableCopies: 2,
    description: 'A comprehensive vocational handbook guiding secondary school students through academic subject combinations, tertiary courses, professional certifications, and modern career paths.',
    summary: 'A comprehensive vocational handbook guiding secondary school students through academic subject combinations, tertiary courses, professional certifications, and modern career paths.',
    coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=700',
    readsCount: 35,
    deweyClass: '300',
    deweyCode: '371.425',
    callNumber: '371.425 AMA',
    ageRange: 'Ages 14-18+',
    readingLevel: 'Lexile 950L',
    pageCount: 194,
    themeColor: 'blue',
    rating: 4.8,
    isPopular: true,
    isNew: true,
  },
  {
    id: 'book-13',
    title: 'Free Bondage',
    author: 'Nevan Bello',
    isbn: '978-978-9659-66-1',
    category: 'Philosophy & Ethics',
    section: 'college',
    totalCopies: 11,
    availableCopies: 11,
    description: 'A profound exploration of mental resilience, personal ethics, and breaking free from self-limiting paradigms, negative habits, and societal pressures.',
    summary: 'A profound exploration of mental resilience, personal ethics, and breaking free from self-limiting paradigms, negative habits, and societal pressures.',
    coverImage: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=700',
    coverUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=700',
    readsCount: 28,
    deweyClass: '100',
    deweyCode: '170.44',
    callNumber: '170.44 BEL',
    ageRange: 'Ages 13-18+',
    readingLevel: 'Lexile 880L',
    pageCount: 156,
    themeColor: 'purple',
    rating: 4.75,
    isPopular: true,
    isNew: true,
  },
  {
    id: 'book-14',
    title: 'Eat That Frog! 21 Great Ways to Stop Procrastinating and Get More Done in Less Time',
    author: 'Brian Tracy',
    isbn: '978-1626569416',
    category: 'Popular',
    section: 'college',
    totalCopies: 1,
    availableCopies: 1,
    description: "There's an old saying that if the first thing you do each morning is eat a live frog, you'll have the satisfaction of knowing you're done with the worst thing you have to do all day. Brian Tracy shows you how to tackle your most critical tasks without procrastination.",
    summary: "There's an old saying that if the first thing you do each morning is eat a live frog, you'll have the satisfaction of knowing you're done with the worst thing you have to do all day. Brian Tracy shows you how to tackle your most critical tasks without procrastination.",
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781626569416-L.jpg',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781626569416-L.jpg',
    readsCount: 110,
    deweyClass: '600',
    deweyCode: '650.11',
    callNumber: '650.11 TRA',
    ageRange: 'Ages 13-18+',
    readingLevel: 'Lexile 980L',
    pageCount: 144,
    themeColor: 'emerald',
    rating: 4.88,
    isPopular: true,
    isNew: true,
    isTeacherPick: true,
  },
  {
    id: 'book-15',
    title: 'Dare to Lead: Brave Work. Tough Conversations. Whole Hearts.',
    author: 'Brené Brown',
    isbn: '978-0399592522',
    category: 'Philosophy & Ethics',
    section: 'college',
    totalCopies: 1,
    availableCopies: 1,
    description: 'Leadership is not about titles, status, and wielding power. Brené Brown teaches us that a leader is anyone who takes responsibility for recognizing the potential in people and ideas, and has the courage to develop that potential through vulnerability and daring.',
    summary: 'Leadership is not about titles, status, and wielding power. Brené Brown teaches us that a leader is anyone who takes responsibility for recognizing the potential in people and ideas, and has the courage to develop that potential through vulnerability and daring.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780399592522-L.jpg',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780399592522-L.jpg',
    readsCount: 88,
    deweyClass: '600',
    deweyCode: '658.4092',
    callNumber: '658.409 BRO',
    ageRange: 'Ages 14-18+',
    readingLevel: 'Lexile 1020L',
    pageCount: 320,
    themeColor: 'rose',
    rating: 4.92,
    isPopular: true,
    isNew: true,
  },
  {
    id: 'book-16',
    title: 'Glow! Be Confident, Be You',
    author: 'Sara Conway',
    isbn: '978-1407197067',
    category: 'Children\'s Fiction',
    section: 'primary',
    totalCopies: 1,
    availableCopies: 1,
    description: 'A vibrant, uplifting guide packed with empowering activities, self-esteem boosters, mindfulness tips, and positive affirmations to help young readers celebrate their unique talents with confidence.',
    summary: 'A vibrant, uplifting guide packed with empowering activities, self-esteem boosters, mindfulness tips, and positive affirmations to help young readers celebrate their unique talents with confidence.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781407197067-L.jpg',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781407197067-L.jpg',
    readsCount: 64,
    deweyClass: '100',
    deweyCode: '158.1',
    callNumber: '158.1 CON',
    ageRange: 'Ages 7-13',
    readingLevel: 'Lexile 680L',
    pageCount: 128,
    themeColor: 'amber',
    rating: 4.82,
    isPopular: true,
    isNew: true,
    isTeacherPick: true,
  },
  {
    id: 'book-17',
    title: 'How to Win Friends and Influence People',
    author: 'Dale Carnegie',
    isbn: '978-0671027032',
    category: 'Popular',
    section: 'college',
    totalCopies: 3,
    availableCopies: 3,
    description: 'One of the most groundbreaking and famous self-help books of all time. Dale Carnegie provides time-tested principles for building genuine relationships, effective communication, empathy, and inspiring enthusiasm in others.',
    summary: 'One of the most groundbreaking and famous self-help books of all time. Dale Carnegie provides time-tested principles for building genuine relationships, effective communication, empathy, and inspiring enthusiasm in others.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780671027032-L.jpg',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780671027032-L.jpg',
    readsCount: 195,
    deweyClass: '100',
    deweyCode: '158.2',
    callNumber: '158.2 CAR',
    ageRange: 'Ages 13-18+',
    readingLevel: 'Lexile 1040L',
    pageCount: 291,
    themeColor: 'indigo',
    rating: 4.96,
    isPopular: true,
    isNew: true,
    isTeacherPick: true,
  },
  {
    id: 'book-18',
    title: 'Gifted Hands: The Ben Carson Story',
    author: 'Ben Carson',
    isbn: '978-0310214694',
    category: 'History & Culture',
    section: 'college',
    totalCopies: 1,
    availableCopies: 1,
    description: 'The inspiring autobiography of Dr. Ben Carson, who overcame childhood poverty and academic struggles in inner-city Detroit through voracious library reading and faith to become Director of Pediatric Neurosurgery at Johns Hopkins Hospital.',
    summary: 'The inspiring autobiography of Dr. Ben Carson, who overcame childhood poverty and academic struggles in inner-city Detroit through voracious library reading and faith to become Director of Pediatric Neurosurgery at Johns Hopkins Hospital.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780310214694-L.jpg',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780310214694-L.jpg',
    readsCount: 142,
    deweyClass: '600',
    deweyCode: '617.48',
    callNumber: '617.48 CAR',
    ageRange: 'Ages 11-18+',
    readingLevel: 'Lexile 920L',
    pageCount: 224,
    themeColor: 'cyan',
    rating: 4.94,
    isPopular: true,
    isNew: true,
    isTeacherPick: true,
  },
  {
    id: 'book-19',
    title: 'The 7 Habits of Highly Effective People',
    author: 'Stephen R. Covey',
    isbn: '978-1982137274',
    category: 'Popular',
    section: 'college',
    totalCopies: 1,
    availableCopies: 1,
    description: 'A transformative holistic approach for solving personal and professional problems. Covey reveals a step-by-step pathway for living with fairness, integrity, honesty, and human dignity based on timeless, enduring principles.',
    summary: 'A transformative holistic approach for solving personal and professional problems. Covey reveals a step-by-step pathway for living with fairness, integrity, honesty, and human dignity based on timeless, enduring principles.',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781982137274-L.jpg',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781982137274-L.jpg',
    readsCount: 175,
    deweyClass: '100',
    deweyCode: '158.1',
    callNumber: '158.1 COV',
    ageRange: 'Ages 14-18+',
    readingLevel: 'Lexile 1080L',
    pageCount: 432,
    themeColor: 'blue',
    rating: 4.93,
    isPopular: true,
    isNew: true,
    isTeacherPick: true,
  },
  {
    id: 'book-20',
    title: 'The 7 Habits of Highly Effective Teens',
    author: 'Sean Covey',
    isbn: '978-1476764665',
    category: 'Popular',
    section: 'college',
    totalCopies: 1,
    availableCopies: 1,
    description: "Adapted from his father's classic, Sean Covey provides a step-by-step guide to help teens improve self-image, build friendships, resist peer pressure, achieve goals, and get along with their parents through engaging cartoons, ideas, and true quotes.",
    summary: "Adapted from his father's classic, Sean Covey provides a step-by-step guide to help teens improve self-image, build friendships, resist peer pressure, achieve goals, and get along with their parents through engaging cartoons, ideas, and true quotes.",
    coverImage: 'https://covers.openlibrary.org/b/isbn/9781476764665-L.jpg',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781476764665-L.jpg',
    readsCount: 162,
    deweyClass: '100',
    deweyCode: '158.108',
    callNumber: '158.108 COV',
    ageRange: 'Ages 12-18',
    readingLevel: 'Lexile 870L',
    pageCount: 288,
    themeColor: 'purple',
    rating: 4.95,
    isPopular: true,
    isNew: true,
    isTeacherPick: true,
  }
];

export const initialCirculation: CirculationRecord[] = [];

export const initialSubmissions: StudentSubmission[] = [];

export const initialAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    title: 'College Annual Literacy Week: Book Review Submissions Open!',
    content: 'We are thrilled to launch this term\'s College Literacy Week! Secondary school students across all year groups are invited to submit critical reviews of their favorite books. The top 3 reviews will win Amazon Kindle readers and custom star badges.',
    date: '2026-06-30',
    category: 'info',
    section: 'college',
  },
  {
    id: 'ann-2',
    title: 'Primary School Reading Hour & Storytelling Circle',
    content: 'Primary Librarian Veronica announces the weekly Storytelling Circle every Thursday afternoon in the Primary School Library Hall. Pupils from Nursery through Primary 6 are warmly welcomed to join in for interactive read-alouds.',
    date: '2026-06-29',
    category: 'info',
    section: 'primary',
  },
  {
    id: 'ann-3',
    title: 'College Overdue Books Return Window (Amnesty Week)',
    content: 'Librarian Alabi has declared an Amnesty Week for all College/Secondary borrowers! All library books returned by July 10th will have overdue flags cleared with zero penalties or library restrictions. Please check your desks and lockers.',
    date: '2026-06-28',
    category: 'alert',
    section: 'college',
  },
  {
    id: 'ann-4',
    title: 'Congratulations to Zainab B. (Primary Reader of the Month!)',
    content: 'A huge round of applause to Zainab Bello in Primary 5B! Zainab has completed 12 library storybooks this month and submitted two insightful book reflections to Librarian Veronica.',
    date: '2026-06-27',
    category: 'achievement',
    section: 'primary',
  }
];
